---

- hosts: all
  become: true
  tasks:

  - name: install apache2 and php package for Ubuntu servers
    apt:
      name:
         - apache2
         - libapache2-mod-php
      state: latest
      when: ansible_distribution == "Ubuntu"

  - name: install apache2 package and php for CentOS servers
    dnf:
      name:
         - httpd
         - php
      state: latest
      when: ansible_distribution == "CentOS"
